# Generated by Django 5.0.1 on 2024-01-24 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa_game', '0004_all_groups_group_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.TextField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secret_santa_game.all_groups')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secret_santa_game.users')),
            ],
        ),
        migrations.CreateModel(
            name='Wishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('drawn_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawn_id', to='secret_santa_game.users')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secret_santa_game.all_groups')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secret_santa_game.users')),
            ],
        ),
    ]
