# Generated by Django 5.0.1 on 2024-01-26 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret_santa_game', '0005_group_chat_wishes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishes',
            name='drawn_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drawn_id', to='secret_santa_game.users'),
        ),
    ]
